---
- name: checking directory {{ elasticsearch_exporter_home }}
  file:
    path: '{{ elasticsearch_exporter_home }}'
    state: directory
    recurse: true

- name: unarchive package
  unarchive:
    src: 'elasticsearch_exporter-1.1.0.linux-amd64.tar.gz'
    dest: '{{ elasticsearch_exporter_home }}'
    extra_opts:
      - --strip-components=1

- name: copy elasticsearch_exporter.service
  template:
    src: elasticsearch_exporter.service.j2
    dest: /lib/systemd/system/elasticsearch_exporter.service
  notify: restart elasticsearch_exporter service

- name: enabling and starting elasticsearch_exporter service
  systemd:
    name: elasticsearch_exporter
    state: started
    enabled: yes
    daemon_reload: yes
