---
- include: install.yml
  when: proxy_url is not defined

- include: install_with_proxy.yml
  when: proxy_url is defined

- name: creating /etc/elasticsearch/elasticsearch.yml configuration file
  template:
    src: "{{ es_config_template }}"
    dest: /etc/elasticsearch/elasticsearch.yml

- name: enabling and starting elasticsearch service
  systemd:
    name: elasticsearch
    state: restarted
    enabled: yes

- name: Pause until cluster is stable
  uri:
    url: "http://localhost:9200/_cluster/health"
    method: GET
    status_code: 200,-1
  register: _result
  until: _result.status == 200 and _result.json.status == "green"
  retries: "{{ stable_rolling_update_retries }}"
  delay: "{{ stable_rolling_update_delay }}"
  become: no
  when: stable_rolling_update

- include: elasticsearch_exporter.yml
  when: elasticsearch_exporter
